Repository Xrayya/java-cli-pbpu, pull requests merged in 2023-11, with the labels that each got.

#4 #3 Add actors model
  .gitignore
  src/main/java/com/Cashier.java
  src/main/java/com/Employee.java
  src/main/java/com/Manager.java
Labels: enhancement

#14 Feat/8 develop log and record
  src/main/java/com/App.java
  src/main/java/com/CashierAppUtil/FoodCategory.java
  src/main/java/com/RecordFiles/employee.json
  src/main/java/com/RecordFiles/menus.json
  src/main/java/com/RecordFiles/orders.json
  src/main/java/com/RecordUtil/Log.java
  src/main/java/com/RecordUtil/Record.java
Labels: enhancement

#12 feat: menu and order
  src/main/java/com/CashierAppUtil/FoodCategory.java
  src/main/java/com/CashierAppUtil/ManagerMachine.java
  src/main/java/com/CashierAppUtil/Menu.java
  src/main/java/com/CashierAppUtil/MenuOrder.java
  src/main/java/com/CashierAppUtil/Order.java
Labels: enhancement

#15 Feat/6 develop cashiermachine
  src/main/java/com/CashierAppUtil/CashierMachine.java
Labels: enhancement

#17 Feat/11 develop app
  .gitignore
  src/main/java/com/App.java
  src/main/java/com/CashierAppUtil/Auth.java
  src/main/java/com/CashierAppUtil/CashierMachine.java
  src/main/java/com/CashierAppUtil/ManagerMachine.java
  src/main/java/com/Model/Cashier.java
  src/main/java/com/Model/Employee.java
  src/main/java/com/Model/Manager.java
  src/main/java/com/RecordFiles/employees.json
Labels: enhancement

#23 feat: implement method editMenu and printAllNewOrder
  src/main/java/com/App.java
  src/main/java/com/CashierAppUtil/CashierMachine.java
Labels: enhancement

#26 21 add menu edit unfinished order
  pom.xml
  src/main/java/com/App.java
  src/main/java/com/CashierAppUtil/FoodCategory.java
Labels: enhancement

#28 I have no idea what is this pr doing, just refactor many things and fix all DONNNEEE
  src/main/java/com/App.java
  src/main/java/com/CashierAppUtil/CashierMachine.java
  src/main/java/com/CashierAppUtil/ManagerMachine.java
  src/main/java/com/Model/Employee.java
  src/main/java/com/Model/EmployeeModel.java
  src/main/java/com/Model/FoodCategory.java
  src/main/java/com/Model/Menu.java
  src/main/java/com/Model/MenuOrder.java
  src/main/java/com/Model/Order.java
  src/main/java/com/RecordFiles/cashiers.json
  src/main/java/com/RecordFiles/managers.json
  src/main/java/com/RecordFiles/menus.json
  src/main/java/com/RecordFiles/orders.json
  src/main/java/com/RecordUtil/Log.java
  src/main/java/com/RecordUtil/Record.java
Labels: bug, enhancement

#25 Feat/9 develop order menuorder and foodcategory
  Diagrams/PBPU-Class Diagram2.png
  Diagrams/PBPU-Class Diagram3.drawio.png
  Diagrams/PBPU-Use Case Diagrams1.png
  Diagrams/PBPU-Use Case Diagrams3.drawio.png
  README.md
Labels: documentation
